
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ARTURO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDepositar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_billete.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, 60));
        jLabel4.getAccessibleContext().setAccessibleName("");

        jLabel2.setText("BancoMex");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 90, -1));

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 80, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 90, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cajero.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(null, "Author: Arturo Salas Hernández\n" + "Grupo: 502-A      Semestre: 5to\n" + "Cajero automático - Versión: 1.0");
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    int capital = 0;
    String valor = "";
    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Toolkit.getDefaultToolkit().beep();

        valor = JOptionPane.showInputDialog("Digite la cantidad a depositar: ");
        if (valor == null || valor.isEmpty()) {
            this.setVisible(true);
        } else {
            int cantidadDinero = Integer.parseInt(valor);

            if (cantidadDinero >= 1) {
                capital += cantidadDinero;
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Deposito realizado exitosamente");
            } else if (cantidadDinero == 0) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Digite un valor diferente a 0");
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Cantidad Invalida");
            }
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Toolkit.getDefaultToolkit().beep();
        int temp = 0, totalRetiro = 0, cantidadBilletes;
        String efectivo = "";

        valor = JOptionPane.showInputDialog("Digite la cantidad a retirar: ");
        if (valor == null || valor.isEmpty()) {
            this.setVisible(true);
        } else {
            int cantidadRetiro = Integer.parseInt(valor);

            if (capital >= cantidadRetiro) {
                if (cantidadRetiro >= 50) {
                    if (cantidadRetiro >= 1000) {
                        cantidadBilletes = cantidadRetiro / 1000;
                        temp = cantidadRetiro % 1000;
                        cantidadRetiro = temp;
                        totalRetiro += cantidadBilletes * 1000;
                        efectivo += "Billete(s) de $1000: " + String.valueOf(cantidadBilletes) + "\n";
                    }
                    if (cantidadRetiro >= 500) {
                        cantidadBilletes = cantidadRetiro / 500;
                        temp = cantidadRetiro % 500;
                        cantidadRetiro = temp;
                        totalRetiro += cantidadBilletes * 500;
                        efectivo += "Billete(s) de $500: " + String.valueOf(cantidadBilletes) + "\n";
                    }
                    if (cantidadRetiro >= 200) {
                        cantidadBilletes = cantidadRetiro / 200;
                        temp = cantidadRetiro % 200;
                        cantidadRetiro = temp;
                        totalRetiro += cantidadBilletes * 200;
                        efectivo += "Billete(s) de $200: " + String.valueOf(cantidadBilletes) + "\n";
                    }
                    if (cantidadRetiro >= 100) {
                        cantidadBilletes = cantidadRetiro / 100;
                        temp = cantidadRetiro % 100;
                        cantidadRetiro = temp;
                        totalRetiro += cantidadBilletes * 100;
                        efectivo += "Billete(s) de $100: " + String.valueOf(cantidadBilletes) + "\n";
                    }
                    if (cantidadRetiro >= 50) {
                        cantidadBilletes = cantidadRetiro / 50;
                        totalRetiro += cantidadBilletes * 50;
                        efectivo += "Billete(s) de $50: " + String.valueOf(cantidadBilletes);
                    }

                    capital -= totalRetiro;
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Retiro realizado exitosamente");
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "El cajero devuelve: \n" + efectivo);
                } else if (cantidadRetiro <= 0) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Cantidad invalida");
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Cantidad minima de retiro: $50 MXN");
                }
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            }
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(null, "Su saldo actual es de: $" + capital + " MXN");
        this.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
